# Generated by Django 4.2.8 on 2023-12-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="thumbnail",
            field=models.ImageField(default="default.png", upload_to="thumbnails"),
        ),
    ]
